'use strict';
const $=id=>document.getElementById(id);let csrf='',state={},selectedRun=null,recording=null;
function message(text){$('message').textContent=text||'';}
async function api(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-QA-CSRF':csrf}:{},body:data?JSON.stringify(data):undefined});const result=await r.json();if(!r.ok)throw Error(result.error||'Request failed');return result;}
function bind(id,fn){$(id).addEventListener('click',async e=>{e.preventDefault();try{message('');await fn();}catch(err){message(err.message);}});}
function tab(name){document.querySelectorAll('.tab').forEach(e=>e.hidden=e.id!==name);document.querySelectorAll('[data-tab]').forEach(e=>e.classList.toggle('active',e.dataset.tab===name));}
document.querySelectorAll('[data-tab]').forEach(e=>e.onclick=()=>tab(e.dataset.tab));
function pid(){const n=Number($('project').value);if(!n)throw Error('Create or select a project first');return n;}
function option(value,text){const o=document.createElement('option');o.value=value;o.textContent=text;return o;}
function textElement(tag,text){const e=document.createElement(tag);e.textContent=text;return e;}
async function refresh(){const previous=$('project').value;state=await api('/api/state'+(previous?'?project='+previous:''));csrf=state.user.csrf;$('identity').textContent=state.user.name+' · '+state.user.role;$('login').hidden=true;$('app').hidden=false;$('logout').hidden=false;
$('project').replaceChildren(option('','Select project'));for(const p of state.projects)$('project').append(option(p.id,p.name));$('project').value=previous||state.projects[0]?.id||'';
if($('project').value&&!state.project){state=await api('/api/state?project='+$('project').value);}renderState();}
function renderState(){$('target').textContent=state.project?.target||'Choose a project';$('workflowSelect').replaceChildren(option('','No workflow selected'));$('savedWorkflows').replaceChildren();for(const w of state.workflows||[]){$('workflowSelect').append(option(w.id,w.name));const b=textElement('button',w.name);b.className='secondary';b.onclick=()=>loadConfig(JSON.parse(w.config));$('savedWorkflows').append(b);}
$('gaps').textContent=(state.workflows||[]).length?'Choose a workflow to verify its expected outcomes. Missing evidence remains an explicit gap.':'No workflow configured. Record a critical flow, add assertions and store its private inputs to test business outcomes.';
$('runs').replaceChildren();for(const run of state.jobs||[]){const tr=document.createElement('tr');for(const value of [new Date(run.created*1000).toLocaleString(),run.kind,run.status])tr.append(textElement('td',value));const td=document.createElement('td'),b=textElement('button','Open');b.onclick=()=>openRun(run.id).catch(e=>message(e.message));td.append(b);tr.append(td);$('runs').append(tr);}
$('reviews').textContent=JSON.stringify(state.reviews||[],null,2);}
$('project').onchange=()=>{selectedRun=null;$('runDetails').hidden=true;refresh().catch(e=>message(e.message));};
$('loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/login',{name:$('username').value,password:$('password').value});csrf=d.csrf;$('password').value='';message('');await refresh();}catch(err){message(err.message);}};
bind('logout',async()=>{await api('/api/logout',{});location.reload();});bind('refresh',refresh);
$('projectForm').onsubmit=async e=>{e.preventDefault();try{const r=await api('/api/project',{name:$('projectName').value,target:$('projectUrl').value});$('project').append(option(r.id,$('projectName').value));$('project').value=r.id;await refresh();message('Project created');}catch(err){message(err.message);}};
async function start(kind,actions=false){const r=await api('/api/run',{project:pid(),kind,actions,workflow:kind==='scan'||kind==='thorough'?Number($('workflowSelect').value)||null:null});await refresh();await openRun(r.id);}
bind('run',()=>start($('kind').value,$('actions').checked));bind('record',()=>start('record',$('recordConsent').checked));bind('install',()=>start('setup'));
async function openRun(id){selectedRun=id;tab('results');await pollRun();}
async function pollRun(){if(!selectedRun)return;const d=await api('/api/job?id='+encodeURIComponent(selectedRun));$('runDetails').hidden=false;$('runTitle').textContent=d.kind+' · '+d.status;$('log').textContent=d.log;$('cancel').hidden=!['RUNNING','QUEUED'].includes(d.status);$('artifacts').replaceChildren();for(const f of d.files){const a=textElement('a',f);a.href='/api/file?id='+encodeURIComponent(d.id)+'&path='+encodeURIComponent(f);a.style.display='block';$('artifacts').append(a);}recording=d.recording;$('loadRecording').hidden=!recording;$('jira').href='/api/issues?id='+d.id+'&format=jira';$('github').href='/api/issues?id='+d.id+'&format=markdown';}
bind('cancel',async()=>{await api('/api/cancel',{id:selectedRun});await pollRun();});
bind('loadRecording',()=>{loadConfig(recording.draft);tab('workflows');message('Recording loaded. Required private inputs: '+recording.required_inputs.join(', ')+'. Review every step and expected outcome before saving.');});
setInterval(async()=>{if(document.hidden||!csrf||!selectedRun)return;try{await pollRun();}catch(e){message(e.message);}},3000);
const actions=['goto','click','fill','press','select','check','uncheck','url','visible','hidden','enabled','disabled','text','value','count'];
function addStep(step={action:'visible',selector:'',value:''}){const row=document.createElement('div');row.className='step';const a=document.createElement('select');for(const action of actions)a.append(option(action,action));a.value=step.action;const s=document.createElement('input');s.placeholder='CSS selector';s.setAttribute('aria-label','CSS selector');s.value=step.selector||'';const v=document.createElement('input');v.placeholder='Expected value / QA_INPUT_NAME';v.setAttribute('aria-label','Expected value or private input name');v.value=step.value_env||step.value||'';const b=textElement('button','Remove');b.className='secondary';b.onclick=()=>row.remove();row.append(a,s,v,b);$('steps').append(row);}
function config(){const steps=[...$('steps').children].map(row=>{const [a,s,v]=row.children,step={action:a.value};if(!['goto','url'].includes(a.value))step.selector=s.value;if(['fill','select'].includes(a.value))step.value_env=v.value;else if(['goto','url','press','text','value','count'].includes(a.value))step.value=a.value==='count'?Number(v.value):v.value;return step;});return {journeys:[{name:$('workflowName').value,path:$('workflowPath').value,critical:true,steps}]};}
function loadConfig(cfg){const j=cfg.journeys?.[0];if(!j)throw Error('JSON requires a journey');if(cfg.journeys.length!==1)throw Error('Visual editor supports one journey per workflow version. Use the CLI for multi-journey configurations.');$('workflowName').value=j.name;$('workflowPath').value=j.path;$('steps').replaceChildren();j.steps.forEach(addStep);$('workflowJson').value=JSON.stringify(cfg,null,2);}
bind('addStep',()=>addStep());bind('importWorkflow',()=>loadConfig(JSON.parse($('workflowJson').value)));
bind('saveWorkflow',async()=>{await api('/api/workflow',{project:pid(),name:$('workflowName').value,config:config()});await refresh();message('Workflow saved as a new version.');});
bind('exportWorkflow',()=>{const blob=new Blob([JSON.stringify(config(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='workflow.json';a.click();URL.revokeObjectURL(url);});
bind('showFindings',async()=>{const data=await api('/api/findings?id='+selectedRun);$('score').textContent=JSON.stringify(data.score,null,2);$('findings').replaceChildren();for(const f of data.findings){const tr=document.createElement('tr');tr.append(textElement('td',f.status));const cell=document.createElement('td'),b=textElement('button',f.check||f.name||f.family);b.className='secondary';b.onclick=()=>{$('findingId').value=f.id||'';};cell.append(b,textElement('small',f.id||''));tr.append(cell,textElement('td',f.detail||''));$('findings').append(tr);}});
bind('saveReview',async()=>{await api('/api/review',{job:selectedRun,finding:$('findingId').value,owner:$('reviewOwner').value,state:$('reviewState').value,note:$('reviewNote').value});await refresh();message('Review recorded. Automated findings remain unchanged.');});
bind('doctor',async()=>{const d=await api('/api/doctor');$('checks').replaceChildren();for(const c of d.checks){const tr=document.createElement('tr');for(const text of [c.name,c.ok?'Available':'Needs setup',c.detail+(c.ok?'':' — '+c.fix)])tr.append(textElement('td',text));$('checks').append(tr);}});
bind('createUser',async()=>{await api('/api/user',{name:$('newUser').value,password:$('newPassword').value,role:$('newRole').value});$('newPassword').value='';message('User created. Grant project access below.');});
bind('grant',async()=>{await api('/api/member',{project:pid(),username:$('member').value});message('Project access granted.');});
bind('saveSecret',async()=>{await api('/api/secret',{project:pid(),name:$('secretName').value,value:$('secretValue').value});$('secretValue').value='';message('Private input saved in the OS credential store.');});
bind('deleteSecret',async()=>{await api('/api/secret-delete',{project:pid(),name:$('secretName').value});message('Private input deleted.');});
bind('purge',async()=>{if(!confirm('Delete completed run artifacts older than the selected retention period?'))return;const r=await api('/api/retention',{days:Number($('retention').value)});message('Purged '+r.purged+' expired runs.');await refresh();});
addStep();refresh().catch(()=>{});

bind('revoke',async()=>{await api('/api/member-remove',{project:pid(),username:$('member').value});message('Project membership revoked. Admin accounts retain global access.');});
bind('resetPassword',async()=>{await api('/api/password',{name:$('newUser').value,password:$('newPassword').value});$('newPassword').value='';message('Password reset; that user’s sessions were invalidated.');});
